### ISSUE TITLE
Executable war

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-webflow-customization#278]
Add embedded tomcat as the provided dependency (to be part of `WEB-INF/lib-provided` but not `lib`) and make it possible to run it via `java -jar`.

**Comment by jnpsk** [comment]
This one runs just fine with the _standalone profile_ on.
- tomcat is not included at all with _standalone profile_ off,.
- tomcat is included in `WEB-INF/lib-provided` with _standalone profile_ on and can be executed using `java -jar`
- `org.apache.tomcat.embed:*:*:*:compile` in `bannedDependencies`
